#!/bin/bash
sleep 1
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-wlr
killall xdg-desktop-portal
killall xdg-desktop-portal-*
/usr/lib64/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib64/xdg-desktop-portal-gtk
sleep 2
/usr/lib/xdg-desktop-portal &
