[mgr]
show_hidden = true

[plugin]
prepend_previewers = [
  {mime = "application/epub+zip", run = "epub-preview"},
  {mime = "*.md", run = "glow"},
  {id = "git", name = "*", run = "git"},
  {id = "git", name = "*/", run = "git"}
]
